# package Overview
package_name: SupplyChainClassifier
# Data Files
training_data_file: llm_alinged_0_1_huge_sc_data.json
# Target  
# The target we are attempting to predict(Supply-Chain)
target: Label
pipeline_name: supplychain_classification_model
pipeline_save_file: supplychain_classification_model_output
features: 
  - sentence
dev_test_split: False
# set train/val/test spilt
val_size: 0.2
test_size: 0.2
# to set the random seed 
random_state: 1

# model args
train_file: llm_alinged_0_1_huge_sc_data.json
base_model: nlpaueb/sec-bert-num
batch_size: 32
clip: false
cuda: '0'
epochs: 7
num_workers: 0
seed: 1
truncate: 512
wandb: true
warmup_smooth: 0.8
weight_decay: 0.001
learning_rate: 0.00005

